# Generated by Django 4.0.1 on 2023-11-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('Name', models.CharField(max_length=64)),
                ('Class', models.CharField(max_length=64)),
                ('Gender', models.CharField(max_length=64)),
                ('Age', models.IntegerField()),
                ('Group', models.CharField(max_length=64)),
                ('Address', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
