# Generated by Django 4.0.1 on 2023-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.IntegerField(),
        ),
    ]
